language: objective-c
before_script:
    - brew update
    - brew unlink xctool
    - brew install -v --HEAD xctool
script:
    - xctool -workspace OpenMRS-iOS.xcworkspace -scheme OpenMRS-iOS test -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
osx_image: xcode611
